### PR TITLE
fixed tests to work with vuetify

### PR DESCRIPTION
**Pull request by ConnorBach**

### CODE REVIEW

**Review by tblazek98 — DISMISSED** [review]
Looks great, solves all the warnings. I wonder if there's a way for us to put all those vuetify imports into a separate file that we can just call for each of the tests. I'd hate to have to copy and paste the whole vuetify thing for every test.

**Comment by ConnorBach** [comment]
Good idea, I'll look into refactoring the tests to allow for reuse of code.

**Comment by ConnorBach** [comment]
Added a test setup file that allows us to remove a line from each test. After some testing it seems like most of the lines are needed to setup the environment unfortunately. I think the easiest thing to do will be to copy an existing test file, rename it and then edit the component that is being tested.

**Comment by tblazek98** [comment]
We talked about this and looks like we couldn't find an easy way to import everything, unfortunate, but not the end of the world to have a similar header

**Review by tblazek98 — APPROVED** [review]
It's nice to not have all those warnings anymore

**Pull request merged**
